### ISSUE TITLE
Fails to build with nw-gyp

### ISSUE THREAD

**Issue by elliottsj** [chjj/pty.js#107]
I'm trying to built pty.js v0.2.5 for use in [nw.js](https://github.com/nwjs/nw.js) (i.e. node-webkit), using [nw-gyp](https://github.com/nwjs/nw-gyp) [since pty.js has native C++ addons](https://github.com/nwjs/nw.js/wiki/Using-Node-modules#3rd-party-modules-with-cc-addons):

```shell
$ cd pty.js
$ npm install
|
> pty.js@0.2.5 install /Users/Spencer/Dropbox/Projects/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node
  SOLINK_MODULE(target) Release/pty.node: Finished
extend@1.2.1 node_modules/extend

nan@1.6.2 node_modules/nan

mocha@1.17.1 node_modules/mocha
├── diff@1.0.7
├── growl@1.7.0
├── commander@2.0.0
├── mkdirp@0.3.5
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
├── debug@2.1.1 (ms@0.6.2)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

$ nw-gyp configure --target=0.11.6
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.10.36 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/Users/Spencer/.nvm/v0.10.36/lib/node_modules/nw-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Spencer/Dropbox/Projects/pty.js/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Spencer/.nvm/v0.10.36/lib/node_modules/nw-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Spencer/.nw-gyp/0.11.6/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Spencer/.nw-gyp/0.11.6',
gyp info spawn args   '-Dmodule_root_dir=/Users/Spencer/Dropbox/Projects/pty.js',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 

$ nw-gyp build
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.10.36 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:200:13: error: no type named 'SetCounterFunction' in 'v8::V8'
    v8::V8::SetCounterFunction(cb);
    ~~~~~~~~^
../node_modules/nan/nan.h:205:13: error: no type named 'SetCreateHistogramFunction' in 'v8::V8'
    v8::V8::SetCreateHistogramFunction(cb);
    ~~~~~~~~^
../node_modules/nan/nan.h:210:13: error: no type named 'SetAddHistogramSampleFunction' in 'v8::V8'
    v8::V8::SetAddHistogramSampleFunction(cb);
    ~~~~~~~~^
../node_modules/nan/nan.h:214:12: error: no member named 'IdleNotification' in 'v8::V8'; did you mean 'NanIdleNotification'?
    return v8::V8::IdleNotification(idle_time_in_ms);
           ^~~~~~~~~~~~~~~~~~~~~~~~
           NanIdleNotification
../node_modules/nan/nan.h:213:19: note: 'NanIdleNotification' declared here
  NAN_INLINE bool NanIdleNotification(int idle_time_in_ms) {
                  ^
../node_modules/nan/nan.h:218:5: error: no member named 'LowMemoryNotification' in 'v8::V8'; did you mean 'NanLowMemoryNotification'?
    v8::V8::LowMemoryNotification();
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    NanLowMemoryNotification
../node_modules/nan/nan.h:217:19: note: 'NanLowMemoryNotification' declared here
  NAN_INLINE void NanLowMemoryNotification() {
                  ^
../node_modules/nan/nan.h:222:5: error: no member named 'ContextDisposedNotification' in 'v8::V8'; did you mean 'NanContextDisposedNotification'?
    v8::V8::ContextDisposedNotification();
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    NanContextDisposedNotification
../node_modules/nan/nan.h:221:19: note: 'NanContextDisposedNotification' declared here
  NAN_INLINE void NanContextDisposedNotification() {
                  ^
6 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Spencer/.nvm/v0.10.36/lib/node_modules/nw-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/Spencer/.nvm/v0.10.36/bin/nw-gyp" "build"
gyp ERR! cwd /Users/Spencer/Dropbox/Projects/pty.js
gyp ERR! node -v v0.10.36
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok 
```

I've also tried node [v0.11.16](https://gist.github.com/elliottsj/0b1ddeda315e178f4d01), [v0.12.0](https://gist.github.com/elliottsj/1159a6efc0e6b1a3069a), and [io.js v1.1.0](https://gist.github.com/elliottsj/de09d76790597893c6f4), all with the same error.

Any idea what's going on here? Is it an issue with [nan](https://github.com/rvagg/nan/) or [nw-gyp](https://github.com/nwjs/nw-gyp)?

**Comment by elliottsj** [comment]
Update: I was able to get pty.js to compile using node v0.10.36 and nw.js v0.10.5:
```shell
$ nw-gyp configure --target=0.10.5
...                                                                      
$ nw-gyp build                    
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.10.36 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node
  SOLINK_MODULE(target) Release/pty.node: Finished
gyp info ok
```
