### ISSUE TITLE
Unable to build: ‘class v8::Object’ has no member named ‘ForceSet’

### ISSUE THREAD

**Issue by 2m** [chjj/pty.js#195]
```
../../nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../src/unix/pty.cc:20:
```

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Linux 4.16.8-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/martynas/node_modules/pty.js
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by ghost** [comment]
Found this, maybe related? https://github.com/nodejs/node/issues/20770

**Comment by ghost** [comment]
i switched my node version to 8 and it installed correctly

**Comment by LoganDark** [comment]
@chjj fix please!

**Comment by keivanh** [comment]
Doesn't work on 11.6.0

**Comment by LoganDark** [comment]
@keivanh **we know**

**Comment by keivanh** [comment]
Any workaround meanwhile? What is max Node version support this?

**Comment by LoganDark** [comment]
@keivanh node 8, the **long term support** version, see https://github.com/chjj/pty.js/issues/195#issuecomment-389651039

**Comment by RossComputerGuy** [comment]
Doesn't work on node v11.12.0

**Comment by gustawdaniel** [comment]
I have this problem on node v10.15.0

**Comment by midnightcodr** [comment]
node 8 is supported till 2019-12-31, what should we do after that?

**Comment by paulirish** [comment]
afaik this project is abandoned. 

https://github.com/Microsoft/node-pty is fork that's maintained by msft and used in vscode. 

It was a perfect drop-in replacement in my project.   g'luck!  🍀

**Comment by liswin** [comment]
You could get this to work on a node v10.x  with @paulirish  answer.

**Comment by LordZardeck** [comment]
This is because of outdated version of nan. However, this project won't work on later versions of node anyway.
