### ISSUE TITLE
Doesnt work on 10.0.0

### ISSUE THREAD

**Issue by LoganMD** [chjj/pty.js#194]
It just wont build, run, or anything.

**Comment by CaptainYarb** [comment]
We were able to run this in NodeJS 10 in a docker container. You may have an issue with your local install or system. Might be worthwhile to get more context to your runtime environment.

**Comment by redders6600** [comment]
@CaptainYarb I also cannot build with 10, I get the error listed in #195.
I'm actually using electron 3 then using `electron-rebuild`.

```
make: Entering directory '/data/hdd/dev/flare-electron/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/unix/pty.cc:20:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
```

**Comment by raziel057** [comment]
Same error on my side with node 11.2.0

**Comment by Tyriar** [comment]
FYI I maintain a fork of pty.js that has advanced quite a bit https://github.com/Microsoft/node-pty
